In [1]:
from sklearn.datasets import make_classification
import torch

In [2]:
# Creating a synthetic dataset
X,y = make_classification(
    n_samples=10, 
    n_features=2,   #Number of features
    n_informative=2,  # Number of informative features
    n_redundant=0,  # Number of redundant features
    n_classes=2,   # Number of classes
    random_state=42
)

In [3]:
print(X, "\n", y)

[[ 1.06833894 -0.97007347]
 [-1.14021544 -0.83879234]
 [-2.8953973   1.97686236]
 [-0.72063436 -0.96059253]
 [-1.96287438 -0.99225135]
 [-0.9382051  -0.54304815]
 [ 1.72725924 -1.18582677]
 [ 1.77736657  1.51157598]
 [ 1.89969252  0.83444483]
 [-0.58723065 -1.97171753]] 
 [1 0 0 0 0 1 1 1 1 0]


In [4]:
# Converting the data Pytorch Tensors
X = torch.tensor(X, dtype=torch.float32)
y = torch.tensor(y, dtype=torch.float32)

In [5]:
from torch.utils.data import Dataset, DataLoader

class CustomDataset(Dataset):
    
    def __init__(self, features, Labels):
        self.features = features
        self.labels = Labels

    def __len__(self):
        return self.features.shape[0]
    
    def __getitem__(self, index):

        # This is where we can apply any transformations if needed

        return self.features[index] , self.labels[index]

In [7]:
dataset = CustomDataset(X,y)

print(len(dataset))
print("\n", dataset[2])

10

 (tensor([-2.8954,  1.9769]), tensor(0.))


In [8]:
# DataLoader 

dataloader = DataLoader(dataset, batch_size=2, shuffle=True)

for batch_features, batch_labels in dataloader:
    print("Batch Features: ", batch_features)
    print("Batch Labels: ", batch_labels)
    print("-"*50)

Batch Features:  tensor([[-1.9629, -0.9923],
        [-0.7206, -0.9606]])
Batch Labels:  tensor([0., 0.])
--------------------------------------------------
Batch Features:  tensor([[ 1.0683, -0.9701],
        [ 1.7273, -1.1858]])
Batch Labels:  tensor([1., 1.])
--------------------------------------------------
Batch Features:  tensor([[-0.5872, -1.9717],
        [ 1.8997,  0.8344]])
Batch Labels:  tensor([0., 1.])
--------------------------------------------------
Batch Features:  tensor([[-1.1402, -0.8388],
        [ 1.7774,  1.5116]])
Batch Labels:  tensor([0., 1.])
--------------------------------------------------
Batch Features:  tensor([[-0.9382, -0.5430],
        [-2.8954,  1.9769]])
Batch Labels:  tensor([1., 0.])
--------------------------------------------------
