In [1]:
import pandas as pd
import numpy as np
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler , LabelEncoder

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [3]:
df.shape

(569, 33)

In [4]:
df.drop(columns = ['id', 'Unnamed: 32'], inplace=True)

In [5]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

In [6]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,1:], df.iloc[:, 0], test_size=0.2, random_state=42)

In [7]:
# Scaling the values on X_train and X_test
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [8]:
# Label Encoding on y_train and y_test
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [9]:
y_train

array([0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1,
       1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0,

##### **Numpy Arrays to PyTorch Tensors**

In [ ]:
# Converting to Tensors
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [11]:
print(X_train_tensor.shape)
print(y_train_tensor.shape)

torch.Size([455, 30])
torch.Size([455])


#### **Build & Train a Single-Layer Neural Network Manually**

##### **Defining the Model**

In [12]:
class MySimpleNN():

    # Constructor
    def __init__(self, X):
        self.weights = torch.rand(X.shape[1], 1, dtype=torch.float64, requires_grad=True)
        self.bias = torch.zeros(1, dtype = torch.float64, requires_grad=True)

    # Forward Propagation
    def forward(self, X):
        z = torch.matmul(X, self.weights) + self.bias  # z= w*x +b
        y_pred = torch.sigmoid(z)
        return y_pred
    
    # Loss Function
    # Clamp Predictions to Avoid log(0)
    def loss_function(self, y_pred, y):
        epsilon = 1e-7
        y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon) 
        # Here, Clamp will replace any value less than epsilon with epsilon and max. value with 1-epsilon


    # Calculate Loss
        loss = -(y_train_tensor * torch.log(y_pred) + (1-y_train_tensor) * torch.log(1-y_pred)).mean()
        return loss

In [13]:
# Imp. Parameters
learning_rate = 0.1
epochs = 25

#### **Training Pipeline**

In [14]:
# Create Model
model = MySimpleNN(X_train_tensor)  # Training Data

# Define Loop/ no. of epochs

for epoch in range(epochs):

    # Forward Pass
    y_pred = model.forward(X_train_tensor)

    # Loss Calculate
    loss = model.loss_function(y_pred, y_train_tensor)

    # Backward Pass
    loss.backward()

    # Parameters Update
    with torch.no_grad():
        model.weights -= learning_rate * model.weights.grad
        model.bias -= learning_rate * model.bias.grad

    # Zero Gradients
    model.weights.grad.zero_()
    model.bias.grad.zero_()

    # Printing Loss for Each Epoch
    print(f"Epoch: {epoch + 1} ,  Loss: {loss.item()}")


Epoch: 1 ,  Loss: 3.8393782364238676
Epoch: 2 ,  Loss: 3.715842377027993
Epoch: 3 ,  Loss: 3.5923869984439203
Epoch: 4 ,  Loss: 3.4632147399993864
Epoch: 5 ,  Loss: 3.3263742411229784
Epoch: 6 ,  Loss: 3.1885908443563435
Epoch: 7 ,  Loss: 3.0506071838691122
Epoch: 8 ,  Loss: 2.9023230848772568
Epoch: 9 ,  Loss: 2.7436199557525627
Epoch: 10 ,  Loss: 2.5851742470249843
Epoch: 11 ,  Loss: 2.4238834849928628
Epoch: 12 ,  Loss: 2.256409772356107
Epoch: 13 ,  Loss: 2.093858452578393
Epoch: 14 ,  Loss: 1.9369348694125192
Epoch: 15 ,  Loss: 1.781606161180894
Epoch: 16 ,  Loss: 1.6324492615631851
Epoch: 17 ,  Loss: 1.4866411521370524
Epoch: 18 ,  Loss: 1.3507309983724223
Epoch: 19 ,  Loss: 1.2306837932404557
Epoch: 20 ,  Loss: 1.1277506312851386
Epoch: 21 ,  Loss: 1.0423315451700113
Epoch: 22 ,  Loss: 0.9739321331420927
Epoch: 23 ,  Loss: 0.921086298578487
Epoch: 24 ,  Loss: 0.8814521845793056
Epoch: 25 ,  Loss: 0.8522200100257593


In [15]:
model.weights # Values after 25 Epochs

tensor([[-0.0836],
        [ 0.1990],
        [ 0.1399],
        [-0.3265],
        [ 0.3139],
        [ 0.0034],
        [-0.0902],
        [ 0.0644],
        [ 0.1463],
        [ 0.0032],
        [ 0.3770],
        [-0.0951],
        [-0.1012],
        [ 0.5241],
        [ 0.1671],
        [-0.0257],
        [-0.2752],
        [-0.1130],
        [ 0.5102],
        [-0.1558],
        [ 0.4294],
        [ 0.2349],
        [-0.4057],
        [ 0.0234],
        [ 0.2648],
        [ 0.2512],
        [-0.2576],
        [-0.3988],
        [ 0.1448],
        [ 0.1651]], dtype=torch.float64, requires_grad=True)

In [37]:
model.bias

tensor([-0.1221], dtype=torch.float64, requires_grad=True)

#### **Model Evaluation**

In [17]:
with torch.no_grad():
    y_pred = model.forward(X_test_tensor)
    y_pred = (y_pred > 0.5).float()
    accuracy = (y_pred == y_test_tensor).float().mean()
    print(f"Accuracy: {accuracy.item()}")

Accuracy: 0.49353647232055664
